/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author david
 */
public class TelaAjuda extends javax.swing.JFrame {

    private TelaInicial telaInicial;
    /**
     * Creates new form TelaAjuda
     */
    public TelaAjuda(TelaInicial telaInicial) {
        this.telaInicial = telaInicial;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Funcionamento básico \n\nAo ligar o computador, o software inicia e pergunta sobre cada objetivo cadastrado (por isso, é importante que você não cadastre muitos objetivos! É sério, é para seu próprio bem!), caso você não tenha desistido, basta confirmar para que o software conte mais um dia! Não se preocupe, ele irá fazer isso apenas uma vez por dia. \n\nCadastrar novo objetivo \n\nSe você quiser cadastrar um novo objetivo no banco de dados, basta clicar no botão “Novo” abaixo da tabela de objetivos cadastrados na tela inicial, será perguntado o nome do objetivo que você quer, se você deseja inserir metas e, se você quiser, pode inserir uma ou mais metas, ao terminar, confirme as informações e salve, a contagem será iniciada no dia em que o objetivo foi criado. \n\nEditar ou excluir um objetivo existente \n\nVocê pode editar ou excluir um dos objetivos da tabela, basta selecionar e clicar no botão “Editar” na tela inicial, edite as informações desejadas e confirme, os dados anteriores serão substituídos. \n\nConfigurações do banco de dados \n\nVocê pode importar, exportar ou excluir o banco de dados do software (Atenção: muito cuidado ao excluir o banco de dados, ele é excluído de verdade!). \n\nDica de ouro \n\nNão seja ganancioso! Não se preocupe em alcançar 200, 300, 500 ou até 1000 dias no seu objetivo, em vez disso, se preocupe com o hoje, cada pequena vitória importa, viver um dia de cada vez vai levar você para lugares inimagináveis! ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        telaInicial.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            //UIManager.setLookAndFeel(new FlatMacDarkLaf());
            com.formdev.flatlaf.intellijthemes.FlatMaterialDesignDarkIJTheme.setup();
 
        } catch (Exception e){
            e.printStackTrace();
        }

        TelaInicial telaInicial = new TelaInicial();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAjuda(telaInicial).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
